# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MainUser\Documents\GitHub\Sema\weather_app\Main_A\country_.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 850)
        MainWindow.setMaximumSize(QtCore.QSize(650, 850))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0.134328 rgba(124, 0, 124, 255), stop:0.781095 rgba(205, 155, 255, 255), stop:0.98 rgba(255, 255, 255, 255), stop:1 rgba(0, 0, 0, 0))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.country_line = QtWidgets.QLineEdit(self.centralwidget)
        self.country_line.setGeometry(QtCore.QRect(30, 50, 581, 31))
        self.country_line.setStyleSheet("background-color: white;\n"
"border-radius:10px;")
        self.country_line.setText("")
        self.country_line.setMaxLength(32766)
        self.country_line.setObjectName("country_line")
        self.city_label = QtWidgets.QLabel(self.centralwidget)
        self.city_label.setGeometry(QtCore.QRect(60, 220, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(440, 20, 171, 20))
        self.date_label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(110, 650, 391, 28))
        self.info_button.setStyleSheet("background-color: rgb(130, 115, 158);\n"
"\n"
"border-radius:10px;")
        self.info_button.setObjectName("info_button")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(290, 310, 301, 241))
        self.img_label.setStyleSheet("border-radius:10px;\n"
"")
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("c:\\Users\\MainUser\\Documents\\GitHub\\Sema\\weather_app\\Main_A\\icons/pngwing.com.png"))
        self.img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_label.setObjectName("img_label")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(60, 270, 181, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.city_line = QtWidgets.QLineEdit(self.centralwidget)
        self.city_line.setGeometry(QtCore.QRect(30, 128, 581, 31))
        self.city_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.city_line.setObjectName("city_line")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 460, 93, 28))
        self.pushButton_3.setStyleSheet("background-color:transparent\n"
"")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\MainUser\\Documents\\GitHub\\Sema\\weather_app\\Main_A\\icons/location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 400, 111, 61))
        self.pushButton_4.setStyleSheet("background-color:transparent")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\MainUser\\Documents\\GitHub\\Sema\\weather_app\\Main_A\\icons/multiple-users-silhouette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.region_label = QtWidgets.QLabel(self.centralwidget)
        self.region_label.setGeometry(QtCore.QRect(90, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.region_label.setFont(font)
        self.region_label.setStyleSheet("background-color:transparent;\n"
"color: rgb(255, 255, 255);")
        self.region_label.setAlignment(QtCore.Qt.AlignCenter)
        self.region_label.setObjectName("region_label")
        self.region_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.region_combobox.setGeometry(QtCore.QRect(30, 89, 581, 31))
        self.region_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px;")
        self.region_combobox.setCurrentText("")
        self.region_combobox.setObjectName("region_combobox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 740, 121, 91))
        self.pushButton.setStyleSheet("background-color: transparent;\n"
"")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\MainUser\\Documents\\GitHub\\Sema\\weather_app\\Main_A\\icons/weather-news.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 770, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setObjectName("label")
        self.population_label = QtWidgets.QLabel(self.centralwidget)
        self.population_label.setGeometry(QtCore.QRect(80, 410, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.population_label.setFont(font)
        self.population_label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.population_label.setAlignment(QtCore.Qt.AlignCenter)
        self.population_label.setObjectName("population_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.country_line.setPlaceholderText(_translate("MainWindow", "Choose a country..."))
        self.city_label.setText(_translate("MainWindow", "Amsterdam"))
        self.date_label.setText(_translate("MainWindow", "ma, 10.29"))
        self.info_button.setText(_translate("MainWindow", "click for more"))
        self.temp_label.setText(_translate("MainWindow", "7 °C"))
        self.city_line.setPlaceholderText(_translate("MainWindow", "Enter a city name..."))
        self.region_label.setText(_translate("MainWindow", "North-Holland"))
        self.label.setText(_translate("MainWindow", "Weather App"))
        self.population_label.setText(_translate("MainWindow", "873,338"))
